# Generated by Django 5.0.11 on 2025-04-09 18:37

import EHS.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lagging_Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=EHS.models.current_date)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('hse_lag_indicator', models.CharField(blank=True, max_length=64, null=True)),
                ('type_of_injury', models.CharField(blank=True, max_length=64, null=True)),
                ('injured_body_part', models.CharField(blank=True, max_length=64, null=True)),
                ('name_of_injured_person', models.CharField(blank=True, max_length=64, null=True)),
                ('severity', models.IntegerField(blank=True, choices=[(1, '1- Negligible (Can lead to First Aid Injury)'), (2, '2- Marginal (Can lead to MTC or RWC injury)'), (3, '3- Critical (Can lead to LTI Injury)'), (4, '4- Catastrophic (Multiple LTI or Fatalities)')], null=True)),
                ('likelihood', models.IntegerField(blank=True, choices=[(1, '1- Unlikely (Very Rare - Once in a Lifetime)'), (2, '2- Remote (Once in 10 Years)'), (3, '3- Occasional (Once in 2 Years)'), (4, '4- Frequent (Once or more in a year)')], null=True)),
                ('risk_factor', models.CharField(blank=True, max_length=10, null=True)),
                ('incident', models.TextField(blank=True, null=True)),
                ('immediate_action', models.TextField(blank=True, null=True)),
                ('investigation_method', models.CharField(blank=True, max_length=64, null=True)),
                ('fact_about_men', models.TextField(blank=True, null=True)),
                ('fact_about_machine', models.TextField(blank=True, null=True)),
                ('fact_about_mother_nature', models.TextField(blank=True, null=True)),
                ('fact_about_measurement', models.TextField(blank=True, null=True)),
                ('fact_about_method', models.TextField(blank=True, null=True)),
                ('fact_about_material', models.TextField(blank=True, null=True)),
                ('fact_about_history', models.TextField(blank=True, null=True)),
                ('why_one', models.TextField(blank=True, null=True)),
                ('why_two', models.TextField(blank=True, null=True)),
                ('why_three', models.TextField(blank=True, null=True)),
                ('why_four', models.TextField(blank=True, null=True)),
                ('why_five', models.TextField(blank=True, null=True)),
                ('direct_root_cause', models.TextField(blank=True, null=True)),
                ('indirect_root_cause', models.TextField(blank=True, null=True)),
                ('psm_failure', models.TextField(blank=True, null=True)),
                ('date_resume_duty', models.DateField(blank=True, null=True)),
                ('mandays_lost', models.IntegerField(blank=True, null=True)),
                ('complience_status', models.CharField(blank=True, max_length=64, null=True)),
                ('complience_status_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lagging_indicator',
            },
        ),
        migrations.CreateModel(
            name='Physical_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'physical_location',
            },
        ),
        migrations.CreateModel(
            name='LaggingCapaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('frp', models.CharField(blank=True, max_length=64, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('compliance_status', models.CharField(blank=True, max_length=64, null=True)),
                ('lagging_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lagging_capa_entry', to='EHS.lagging_indicator')),
            ],
            options={
                'db_table': 'lagging_capa_entry',
            },
        ),
        migrations.CreateModel(
            name='LeadingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('leading_abnormality', models.CharField(max_length=30)),
                ('initiated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
                ('risk_factor', models.CharField(blank=True, max_length=10, null=True)),
                ('observation_description', models.TextField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('psl_member_name', models.CharField(blank=True, max_length=64, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=64, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('preventive_action', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('physical_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EHS.physical_location')),
            ],
            options={
                'db_table': 'leading_records',
            },
        ),
        migrations.AddField(
            model_name='lagging_indicator',
            name='physical_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EHS.physical_location'),
        ),
    ]
