# Generated by Django 5.0.11 on 2025-05-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EHS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PSSRJobRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "moc_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="MOC No"
                    ),
                ),
                (
                    "job_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Job Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "PSSR Job Record",
                "verbose_name_plural": "PSSR Job Records",
                "db_table": "pssr_job_record",
            },
        ),
        migrations.CreateModel(
            name="PSSRObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observar",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="FPR"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observation"),
                ),
                (
                    "fpr",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="FPR"
                    ),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="Target Date"),
                ),
                (
                    "rpn_category",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B")],
                        max_length=1,
                        null=True,
                        verbose_name="RPN Category",
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Omitted", "Omitted"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Compliance Status",
                    ),
                ),
                (
                    "compliance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Compliance Date"
                    ),
                ),
                (
                    "job_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="EHS.pssrjobrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "PSSR Observation",
                "verbose_name_plural": "PSSR Observations",
                "db_table": "pssr_observation",
            },
        ),
    ]
