# Generated by Django 5.0.11 on 2025-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EHS", "0002_pssrjobrecord_pssrobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lagging_indicator",
            name="Contractor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lagging_indicator",
            name="risk_factor",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="laggingcapaentry",
            name="capa",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
