# Generated by Django 5.0.11 on 2025-06-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CONTRACT", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorReqActManpower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "contractor_req_act_manpower",
            },
        ),
        migrations.DeleteModel(
            name="ContractorDailyRequirement",
        ),
        migrations.RemoveField(
            model_name="contractormanpowerattendance",
            name="e_bolck_17_production",
        ),
        migrations.AddField(
            model_name="contractormanpowerattendance",
            name="e_block_17_production",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="a_block",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="b_block",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="boiler",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="c_block",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="d_block",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="dozer_driver",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="ele",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="gardenar",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="housekeeping_16_17_18",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="inst",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="mee_etp",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="mnts",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="office_boy",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="ohc",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="painting",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="pilot",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="pkg",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="qc_pd",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="rm_engg_16_17_18",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractormanpowerattendance",
            name="ro_plant",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractorreqactmanpower",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="CONTRACT.contractormanpowerattendance",
            ),
        ),
        migrations.AddField(
            model_name="contractorreqactmanpower",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CONTRACT.departmentmanpowerrequirement",
            ),
        ),
    ]
