# Generated by Django 5.0.11 on 2025-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CONTRACT", "0002_contractorreqactmanpower_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "contractor_name",
                    models.CharField(
                        choices=[
                            ("Aldar", "Aldar"),
                            ("Yash", "Yash"),
                            ("ACP", "ACP"),
                            ("HE", "HE"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("A", "A"), ("G", "G"), ("B", "B"), ("C", "C")],
                        max_length=1,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("A Block", "A Block"),
                            ("B Block", "B Block"),
                            ("C Block", "C Block"),
                            ("D Block", "D Block"),
                            ("PKG", "PKG"),
                            ("Pilot", "Pilot"),
                            ("E Block- 17 Production", "E Block- 17 Production"),
                            ("MEE/ETP", "MEE/ETP"),
                            ("RO Plant", "RO Plant"),
                            ("MNTS", "MNTS"),
                            ("ELE", "ELE"),
                            ("INST", "INST"),
                            ("RM/ENGG 16 - 17 & 18", "RM/ENGG 16 - 17 & 18"),
                            ("QC & PD", "QC & PD"),
                            ("Boiler", "Boiler"),
                            ("Dozer Driver", "Dozer Driver"),
                            ("HouseKeeping 16 - 17 & 18", "HouseKeeping 16 - 17 & 18"),
                            ("Office Boy", "Office Boy"),
                            ("Gardenar", "Gardenar"),
                            ("OHC", "OHC"),
                            ("Painting", "Painting"),
                            ("MNTS-E 17", "MNTS-E 17"),
                            ("ELE- E-17", "ELE- E-17"),
                            ("INST-E-17", "INST-E-17"),
                        ],
                        max_length=50,
                    ),
                ),
                ("emp_count", models.PositiveIntegerField()),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCOUNTS", "ACCOUNTS"),
                            ("BOILER UTILITY", "BOILER UTILITY"),
                            ("ELECTRICAL", "ELECTRICAL"),
                            ("EHS", "EHS"),
                            ("HR ADMIN", "HR ADMIN"),
                            ("INSTRUMENT", "INSTRUMENT"),
                            ("IT", "IT"),
                            ("MAINTENANCE", "MAINTENANCE"),
                            ("OPERATION", "OPERATION"),
                            ("PRODUCTION", "PRODUCTION"),
                            ("QA/QC", "QA/QC"),
                            ("SECURITY", "SECURITY"),
                            ("STORE", "STORE"),
                            ("ETP", "ETP"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "contractor_worker",
            },
        ),
    ]
