# Generated by Django 5.0.11 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CONTRACT", "0003_contractorworker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorworker",
            name="emp_count",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="contractorworker",
            name="location",
            field=models.CharField(
                choices=[
                    ("A Block", "A Block"),
                    ("B Block", "B Block"),
                    ("C Block", "C Block"),
                    ("D Block", "D Block"),
                    ("E Block- 17 Production", "E Block- 17 Production"),
                    ("PKG", "PKG"),
                    ("Pilot", "Pilot"),
                    ("MEE/ETP", "MEE/ETP"),
                    ("RO Plant", "RO Plant"),
                    ("MNTS", "MNTS"),
                    ("ELE", "ELE"),
                    ("INST", "INST"),
                    ("RM/ENGG 16 - 17 & 18", "RM/ENGG 16 - 17 & 18"),
                    ("QC & PD", "QC & PD"),
                    ("Boiler", "Boiler"),
                    ("Dozer Driver", "Dozer Driver"),
                    ("HouseKeeping 16 - 17 & 18", "HouseKeeping 16 - 17 & 18"),
                    ("Office Boy", "Office Boy"),
                    ("Gardenar", "Gardenar"),
                    ("OHC", "OHC"),
                    ("Painting", "Painting"),
                    ("MNTS-E 17", "MNTS-E 17"),
                    ("ELE- E-17", "ELE- E-17"),
                    ("INST-E-17", "INST-E-17"),
                ],
                max_length=50,
            ),
        ),
    ]
