# Generated by Django 5.0.11 on 2025-07-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CONTRACT", "0004_alter_contractorworker_emp_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractEmpDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "contract_employee_dept",
            },
        ),
        migrations.CreateModel(
            name="ContractEmployee",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_type", models.CharField(max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="CONTRACT.contractempdepartment",
                    ),
                ),
            ],
            options={
                "db_table": "contract_employee",
            },
        ),
    ]
