# Generated by Django 5.0.11 on 2025-04-08 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                ("invoice", models.CharField(max_length=100, null=True)),
                ("name_of_supplier", models.CharField(max_length=100)),
                ("material", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                ("qty", models.IntegerField()),
                ("reporting_date", models.DateField()),
                ("report_time", models.TimeField()),
                ("unloading_date", models.DateField(blank=True, null=True)),
                ("unloading_time", models.TimeField(blank=True, null=True)),
                ("unloading_days", models.IntegerField(default=0)),
                ("vehicle_no", models.CharField(max_length=100)),
                ("name_of_transporter", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                (
                    "manufacture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "vehicle",
            },
        ),
    ]
