# Generated by Django 5.0.11 on 2025-07-12 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DOM", "Domestic"), ("EXP", "Export")],
                        default="DOM",
                        max_length=3,
                    ),
                ),
                ("material_name", models.CharField(max_length=150)),
                ("trade_name", models.CharField(blank=True, max_length=150)),
                (
                    "unit",
                    models.CharField(help_text="e.g. Kg / Litre / Nos", max_length=30),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Quantity"
                    ),
                ),
                (
                    "tentative_date",
                    models.DateField(verbose_name="Tentative Needed Date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dispatch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                ("invoice", models.CharField(max_length=100, null=True)),
                ("name_of_supplier", models.CharField(max_length=100)),
                ("material", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                ("qty", models.FloatField()),
                ("reporting_date", models.DateField()),
                ("report_time", models.TimeField()),
                ("unloading_date", models.DateField(blank=True, null=True)),
                ("unloading_time", models.TimeField(blank=True, null=True)),
                (
                    "unloading_days",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("vehicle_no", models.CharField(max_length=100)),
                ("name_of_transporter", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                (
                    "manufacture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "vehicle",
            },
        ),
    ]
