# Generated by Django 5.0.11 on 2025-04-08 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("STORE", "0001_initial"),
    ]

    operations = []
