# Generated by Django 5.0.11 on 2025-04-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STORE", "0002_auto_20250408_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="unloading_days",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
