# Generated by Django 5.0.11 on 2025-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STORE", "0003_alter_vehicle_unloading_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="qty",
            field=models.FloatField(),
        ),
    ]
