# Generated by Django 5.0.11 on 2025-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("PRODUCTION", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Downtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                (
                    "ideal",
                    models.CharField(blank=True, default="No", max_length=5, null=True),
                ),
                ("eqpt_id", models.CharField(max_length=50, null=True)),
                ("eqpt_name", models.CharField(max_length=100, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stage_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("batch_no", models.CharField(blank=True, max_length=50, null=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("start_time", models.TimeField(null=True)),
                ("end_time", models.TimeField(null=True)),
                ("total_duration", models.FloatField(null=True)),
                ("block", models.CharField(max_length=50, null=True)),
                ("downtime_dept", models.CharField(max_length=255, null=True)),
                (
                    "downtime_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason", models.TextField(null=True)),
                ("bom_qty", models.FloatField(blank=True, null=True)),
                ("bct", models.FloatField(blank=True, null=True)),
                ("loss", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "downtime",
            },
        ),
    ]
