# Generated by Django 5.0.11 on 2025-04-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTION', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtime',
            old_name='ideal',
            new_name='idle',
        ),
    ]
