# Generated by Django 5.0.11 on 2025-04-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0002_alter_dailycheckin_employee_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="On_Duty_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("employment_status", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=100)),
                ("business_unit", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=50)),
                ("sub_branch", models.CharField(max_length=50)),
                ("request_type", models.CharField(max_length=50)),
                ("attendance_date", models.DateField()),
                ("attendance_day", models.CharField(max_length=15)),
                (
                    "on_duty_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shift_code", models.CharField(max_length=50)),
                ("shift_timings", models.CharField(max_length=50)),
                (
                    "actual_punch_in_out",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("punch_in_date", models.DateField(blank=True, null=True)),
                ("punch_out_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("request_status", models.CharField(max_length=50)),
                ("request_by", models.CharField(max_length=100)),
                ("request_on", models.DateTimeField()),
                (
                    "pending_with",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                ("approver_remark", models.TextField(blank=True, null=True)),
                (
                    "billable_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "punch_in_timing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "punch_out_timing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "on_duty_request",
            },
        ),
        migrations.AddField(
            model_name="dailycheckin",
            name="source",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
