# Generated by Django 5.0.11 on 2025-04-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0003_on_duty_request_dailycheckin_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Helpdesk_Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("employment_status", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=100)),
                ("business_unit", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=50)),
                ("sub_branch", models.CharField(max_length=50)),
                ("ticket_id", models.CharField(max_length=100)),
                ("ticket_details", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("priority", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("raised_on", models.DateTimeField()),
                ("assigned_to", models.CharField(max_length=100)),
                (
                    "pending_with",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("closed_by", models.CharField(blank=True, max_length=100, null=True)),
                ("closed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "is_closed_on_time",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "feedback_rating",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("was_ticket_escalated", models.CharField(max_length=10)),
                (
                    "escalated_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rca", models.TextField(blank=True, null=True)),
                (
                    "time_to_close",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "helpdesk_ticket",
            },
        ),
        migrations.CreateModel(
            name="OvertimeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("employment_status", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=100)),
                ("business_unit", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=50)),
                ("sub_branch", models.CharField(max_length=50)),
                ("attendance_date", models.DateField()),
                ("attendance_day", models.CharField(max_length=15)),
                ("shift_code", models.CharField(max_length=50)),
                ("shift", models.CharField(max_length=100)),
                ("shift_timings", models.CharField(max_length=50)),
                ("punch_in_time", models.CharField(max_length=10)),
                ("punch_out_time", models.CharField(max_length=10)),
                ("working_hours", models.CharField(max_length=10)),
                ("overtime_hours", models.CharField(max_length=10)),
                ("request_status", models.CharField(max_length=50)),
                ("request_by", models.CharField(max_length=100)),
                ("request_on", models.DateField()),
                (
                    "pending_with",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("approver_remark", models.TextField(blank=True, null=True)),
                ("overtime_minutes", models.IntegerField()),
            ],
            options={
                "db_table": "overtime_report",
            },
        ),
        migrations.CreateModel(
            name="ShortLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("employment_status", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=100)),
                ("business_unit", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=50)),
                ("sub_branch", models.CharField(max_length=50)),
                ("request_type", models.CharField(max_length=50)),
                ("attendance_date", models.DateField()),
                ("attendance_day", models.CharField(max_length=15)),
                ("shift_code", models.CharField(max_length=50)),
                ("shift_timings", models.CharField(max_length=50)),
                (
                    "actual_punch_in_out",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("punch_in_date", models.DateField()),
                ("punch_in_timing", models.CharField(max_length=10)),
                ("punch_out_date", models.DateField()),
                ("punch_out_timing", models.CharField(max_length=10)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("request_status", models.CharField(max_length=50)),
                ("request_by", models.CharField(max_length=100)),
                ("request_on", models.DateField()),
                (
                    "pending_with",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("approver_remark", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "short_leave",
            },
        ),
    ]
