# Generated by Django 5.0.11 on 2025-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0004_helpdesk_ticket_overtimereport_shortleave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overtimereport",
            name="approved_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="overtimereport",
            name="request_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
