# Generated by Django 5.0.11 on 2025-07-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0005_alter_overtimereport_approved_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overtimereport",
            name="pending_with",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
