# Generated by Django 5.0.11 on 2025-07-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CANTEEN", "0002_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="CANTEEN.shift",
            ),
        ),
    ]
