# Generated by Django 5.0.11 on 2025-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CANTEEN", "0003_alter_attendance_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Company", "Company"),
                    ("Trainee", "Trainee"),
                    ("Guest", "Guest"),
                    ("Casual", "Casual"),
                ],
                default="company",
                max_length=20,
                null=True,
            ),
        ),
    ]
