# Generated by Django 5.0.11 on 2025-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("head_office", "Head Office"),
                            ("solapur", "Solapur"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("device", models.CharField(blank=True, max_length=255, null=True)),
                ("lan_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("wan_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("port_no", models.PositiveIntegerField(blank=True, null=True)),
                ("frwd_to", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("user_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "old_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "new_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("reset", "Reset"), ("created", "Created")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("action_date", models.DateTimeField(blank=True, null=True)),
                ("expiry_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "credentials",
            },
        ),
    ]
