# Generated by Django 5.0.11 on 2025-07-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spec",
            options={"ordering": ["product", "group", "name"]},
        ),
        migrations.AlterUniqueTogether(
            name="spec",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="qcentry",
            name="general_remarks",
            field=models.TextField(
                blank=True,
                help_text="General remarks entered by QC (up to 250 characters).",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="qcentry",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="Which specs group was used when entering QC results.",
                max_length=100,
                verbose_name="Specification Group",
            ),
        ),
        migrations.AddField(
            model_name="qcentry",
            name="selected_group",
            field=models.CharField(
                blank=True,
                help_text="Which specification group was selected when entering QC results.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="spec",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="Heading for this spec batch, e.g. '8 hr', '15 hr', etc.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spec",
            unique_together={("product", "group", "name")},
        ),
    ]
