# Generated by Django 5.0.11 on 2025-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractorWages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contractor_name",
                    models.CharField(
                        choices=[
                            ("Pratap Enterprises", "Pratap Enterprises"),
                            ("Yogesh Waghmode", "Yogesh Waghmode"),
                            ("Yash Enterprises", "Yash Enterprises"),
                            ("Shital Shinde Services", "Shital Shinde Services"),
                            ("Abhi Consultancy", "Abhi Consultancy"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "contractor_wages ",
            },
        ),
        migrations.CreateModel(
            name="HRBudgetAMC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                ("amc_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_amc",
            },
        ),
        migrations.CreateModel(
            name="HrBudgetCanteen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Balaji Tea Corner", "Balaji Tea Corner"),
                            ("Dayanand Mhetre", "Dayanand Mhetre"),
                            ("Ambika Pure Wage", "Ambika Pure Wage"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_canteen",
            },
        ),
        migrations.CreateModel(
            name="HRBudgetCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "invoice_name",
                    models.CharField(
                        choices=[
                            ("Internet Tata", "Internet Tata"),
                            ("NAS Net", "NAS Net"),
                            ("JIO - Sim", "JIO - Sim"),
                            ("VI - Sim", "VI - Sim"),
                            ("New Mobile", "New Mobile"),
                            (
                                "EPABX - Intercome (Jio PRI)",
                                "EPABX - Intercome (Jio PRI)",
                            ),
                            ("IT material - CCTV", "IT material - CCTV"),
                            ("Hard Disck", "Hard Disck"),
                            ("Tonner", "Tonner"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_communication",
            },
        ),
        migrations.CreateModel(
            name="HRBudgetGeneralAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Printing", "Printing"),
                            ("Stationary", "Stationary"),
                            ("Cleaning Material", "Cleaning Material"),
                            ("Harshada Courier Services", "Harshada Courier Services"),
                            ("Courier (Sample to Vasai)", "Courier (Sample to Vasai)"),
                            ("Pest Control", "Pest Control"),
                            (
                                "Sunshine Services Xerox Conon 16 Admin",
                                "Sunshine Services Xerox Conon 16 Admin",
                            ),
                            (
                                "Sunshine Services Xerox Conon QC Lab",
                                "Sunshine Services Xerox Conon QC Lab",
                            ),
                            (
                                "Sunshine Services Xerox Conon E18 Admin",
                                "Sunshine Services Xerox Conon E18 Admin",
                            ),
                            (
                                "Sunshine Services Xerox Conon 17 Admin",
                                "Sunshine Services Xerox Conon 17 Admin",
                            ),
                            ("Fridge repairing", "Fridge repairing"),
                            ("Water bottle", "Water bottle"),
                            ("Aquaguard/RO", "Aquaguard/RO"),
                            (
                                "Balanand Kirana / Shri Datta Kirana (Jagerry)",
                                "Balanand Kirana / Shri Datta Kirana (Jagerry)",
                            ),
                            ("Pantry", "Pantry"),
                            ("Conveyance", "Conveyance"),
                            ("Post Office", "Post Office"),
                            ("Night round police", "Night round police"),
                            (
                                "Air Conditioner - Services",
                                "Air Conditioner - Services",
                            ),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_general_admin",
            },
        ),
        migrations.CreateModel(
            name="HRBudgetGuestHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Manmeet", "Manmeet"),
                            ("Haripadam", "Haripadam"),
                            ("New guest house", "New guest house"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Rent", "Rent"),
                            ("Maintenance", "Maintenance"),
                            (
                                "Grocery/Vegetables/Milk/Curd/Laundary",
                                "Grocery/Vegetables/Milk/Curd/Laundary",
                            ),
                            ("A/c Servicing", "A/c Servicing"),
                            ("Cleaning Boy", "Cleaning Boy"),
                            ("DISH Recharge", "DISH Recharge"),
                            ("House Keeping", "House Keeping"),
                            ("Light bill", "Light bill"),
                            ("Guest House Cook", "Guest House Cook"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_guesthouse",
            },
        ),
        migrations.CreateModel(
            name="HrBudgetMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "doctor_hospital_name",
                    models.CharField(
                        choices=[
                            ("Dr. Ganesh Atwade(FMO)", "Dr. Ganesh Atwade(FMO)"),
                            ("Baladava Hospital", "Baladava Hospital"),
                            ("Dr. Chidgupkar Hospital", "Dr. Chidgupkar Hospital"),
                            ("Doctor Ukarande", "Doctor Ukarande"),
                            ("Medicines for OHC", "Medicines for OHC"),
                            (
                                "New joinee health check up",
                                "New joinee health check up",
                            ),
                            ("Annual Health Check up", "Annual Health Check up"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_medical",
            },
        ),
        migrations.CreateModel(
            name="HRBudgetTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_training",
            },
        ),
        migrations.CreateModel(
            name="HrBudgetTravellingLodging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (
                                "Vaishnavi/Raghvendra/Darshan Tours & Travels",
                                "Vaishnavi/Raghvendra/Darshan Tours & Travels",
                            ),
                            ("Balaji Sarovar Premire", "Balaji Sarovar Premire"),
                            ("Hotel Lotus", "Hotel Lotus"),
                            ("Hotel Kyriad", "Hotel Kyriad"),
                            (
                                "Hotel Sai Prasad Executive",
                                "Hotel Sai Prasad Executive",
                            ),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_travelling_lodging",
            },
        ),
        migrations.CreateModel(
            name="HrBudgetVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "vehicle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily Pickup-drop", "Daily Pickup-drop"),
                            ("Fuel expense", "Fuel expense"),
                            ("Insurance", "Insurance"),
                            ("Repair & Maintenance", "Repair & Maintenance"),
                            ("Material / Goods", "Material / Goods"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_vehicle",
            },
        ),
        migrations.CreateModel(
            name="HrBudgetWelfare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "welfare_name",
                    models.CharField(
                        choices=[
                            ("Uniform", "Uniform"),
                            ("Employee Engagement", "Employee Engagement"),
                            ("Open house meeting", "Open house meeting"),
                            ("DiwaliSweets", "DiwaliSweets"),
                        ],
                        max_length=100,
                    ),
                ),
                ("bill_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hrbudget_welfare",
            },
        ),
        migrations.CreateModel(
            name="InsuranceMediclaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Insurance Mediclaim GMP", "Insurance Mediclaim GMP"),
                            ("GPAP", "GPAP"),
                            ("WC Policy", "WC Policy"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "insurance_mediclaim",
            },
        ),
        migrations.CreateModel(
            name="SecurityWages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contractor_name",
                    models.CharField(
                        choices=[
                            ("Badalapur Enterprises", "Badalapur Enterprises"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "security_wages ",
            },
        ),
    ]
