# Generated by Django 5.0.11 on 2025-07-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KFFactorEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "kf_factor",
            },
        ),
        migrations.CreateModel(
            name="KFFactorEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_weight_mg",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "burette_reading_ml",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="R_and_D.kffactorentry",
                    ),
                ),
            ],
            options={
                "db_table": "kf_factor_line",
            },
        ),
        migrations.CreateModel(
            name="RDMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Analyst", "Analyst"),
                            ("Product", "Product"),
                            ("Unit", "Unit"),
                            ("Instrument", "Instrument"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "R & D Master",
                "db_table": "r_and_d_master",
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="R_and_D_Moisture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="Entry Date")),
                ("entry_time", models.TimeField(verbose_name="Entry Time")),
                (
                    "eln_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ELN ID"
                    ),
                ),
                ("batch_no", models.CharField(max_length=100, verbose_name="Batch No")),
                (
                    "sample_description",
                    models.CharField(max_length=255, verbose_name="Sample Description"),
                ),
                (
                    "factor_mg_per_ml",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Factor (mg/mL)"
                    ),
                ),
                (
                    "sample_weight_gm",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Sample Weight (gm)",
                    ),
                ),
                (
                    "burette_reading_ml",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Burette Reading (mL)",
                    ),
                ),
                (
                    "moisture_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Moisture (%)"
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                (
                    "completed_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Completed Time"
                    ),
                ),
                (
                    "analysed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Analyst"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moisture_analysts",
                        to="R_and_D.rdmaster",
                        verbose_name="Analysed By",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        limit_choices_to={"category": "Instrument"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moisture_instruments",
                        to="R_and_D.rdmaster",
                        verbose_name="Instrument",
                    ),
                ),
                (
                    "product_name",
                    models.ForeignKey(
                        limit_choices_to={"category": "Product"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moisture_products",
                        to="R_and_D.rdmaster",
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        limit_choices_to={"category": "Unit"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moisture_units",
                        to="R_and_D.rdmaster",
                        verbose_name="Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "R&D Moisture",
                "verbose_name_plural": "R&D Moisture",
                "db_table": "r_and_d_moisture",
            },
        ),
        migrations.AddField(
            model_name="kffactorentry",
            name="analysed_by",
            field=models.ForeignKey(
                limit_choices_to={"category": "Analyst"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kf_entries_analysed",
                to="R_and_D.rdmaster",
            ),
        ),
        migrations.AddField(
            model_name="kffactorentry",
            name="instrument",
            field=models.ForeignKey(
                limit_choices_to={"category": "Instrument"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kf_entries_instrument",
                to="R_and_D.rdmaster",
            ),
        ),
    ]
