# Generated by Django 5.0.11 on 2025-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="product_name",
            field=models.CharField(max_length=100, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="rdmaster",
            name="category",
            field=models.CharField(
                choices=[
                    ("Analyst", "Analyst"),
                    ("Unit", "Unit"),
                    ("Instrument", "Instrument"),
                ],
                max_length=20,
            ),
        ),
    ]
