# Generated by Django 5.0.11 on 2025-04-22 16:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EffluentRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "record_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("stage_name", models.CharField(blank=True, max_length=255, null=True)),
                ("batch_no", models.CharField(blank=True, max_length=50, null=True)),
                ("voucher_no", models.CharField(blank=True, max_length=50, null=True)),
                ("block", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "effluent_records",
            },
        ),
        migrations.CreateModel(
            name="GeneralEffluent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("record_date", models.DateField(auto_now_add=True)),
                ("category", models.CharField(default="Unprocess", max_length=20)),
                (
                    "effluent_nature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("actual_quantity", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "general_effluent",
            },
        ),
        migrations.CreateModel(
            name="EffluentQty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=20)),
                (
                    "effluent_nature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("plan_quantity", models.FloatField(default=0.0)),
                ("actual_quantity", models.FloatField(default=0.0)),
                (
                    "effluent_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qty_units",
                        to="ETP.effluentrecord",
                    ),
                ),
            ],
            options={
                "db_table": "effluent_qty",
            },
        ),
    ]
