# Generated by Django 5.0.11 on 2025-04-22 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generaleffluent",
            name="category",
        ),
        migrations.AddField(
            model_name="generaleffluent",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="generaleffluent",
            name="record_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
