# Generated by Django 5.0.11 on 2025-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0003_effluentqty_quantity_kg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doc_no", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("bom_id", models.CharField(blank=True, max_length=50, null=True)),
                ("product_id", models.CharField(max_length=255)),
                ("stage_name", models.CharField(blank=True, max_length=100, null=True)),
                ("block", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "production_quantity",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "equipment_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "equipment_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "bct_in_hrs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "no_of_batches",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "batch_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "wait_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("scheduling_approach", models.IntegerField(default=0)),
                ("bom_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "production_schedule",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionScheduleLine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("line_type", models.CharField(max_length=20)),
                (
                    "material_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity", models.FloatField(default=0.0)),
                ("ratio", models.FloatField(default=1.0)),
                ("density", models.FloatField(default=0.0)),
                ("litre", models.FloatField(default=0.0)),
                ("include_in_total", models.BooleanField(default=True)),
                ("closed", models.BooleanField(default=False)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "equipment_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("std_bct", models.FloatField(default=0.0)),
                ("wait_time", models.FloatField(default=0.0)),
                (
                    "equipment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "capacity_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "moc_equipment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("star", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "production_schedule_lines",
                "managed": False,
            },
        ),
    ]
